const bpm = [
  { value: 'Very Slow: less than 85', weight: 1 },
  { value: 'Slow: 85-105', weight: 1 },
  { value: 'Slowish: 105-125', weight: 3 },
  { value: 'Medium: 125-145', weight: 5 },
  { value: 'Fast: 145-165', weight: 5 },
  { value: 'Faster: 165-185', weight: 2 },
  { value: 'Punk: 185-205', weight: 1 },
  { value: 'Metal: 205+', weight: 1 },
];

const harmony = [
  { value: 'Acoustic Guitar', weight: 1 },
  { value: 'Electric Guitar', weight: 1 },
  { value: 'Bass Guitar', weight: 1 },
  { value: 'Banjo', weight: 1 },
  { value: 'Ukulele', weight: 1 },
  { value: 'Keyboard / Synth', weight: 1 },
  { value: 'Vocal Harmonies', weight: 1 },
  { value: 'Vocoder Vocals', weight: 1 },
  { value: 'Autotuned Noise / Sample', weight: 1 },
  { value: 'Melodica', weight: 1 },
  { value: 'Slide Electric Guitar', weight: 1 },
  { value: 'Slide Acoustic Guitar', weight: 1 },
  { value: 'Harmonium', weight: 1 },
  { value: 'Autotuned Noise', weight: 1 },
  { value: 'Rhodes', weight: 1 },
];

const key = [
  { value: 'A', weight: 1 },
  { value: 'Bb', weight: 1 },
  { value: 'B', weight: 1 },
  { value: 'C', weight: 1 },
  { value: 'C#', weight: 1 },
  { value: 'D', weight: 1 },
  { value: 'Eb', weight: 1 },
  { value: 'E', weight: 1 },
  { value: 'F', weight: 1 },
  { value: 'F#', weight: 1 },
  { value: 'G', weight: 1 },
  { value: 'Ab', weight: 1 },
];

const lyricDelivery = [
  { value: 'Weird Aggressive (Modest Mouse)', weight: 1 },
  { value: 'Old Punk / Weird (Talking Heads)', weight: 1 },
  { value: 'Crooning', weight: 1 },
  { value: 'Haunting', weight: 1 },
  { value: 'Jazzy', weight: 1 },
  { value: 'Oaky / Folky (The National)', weight: 1 },
  { value: 'Falsetto', weight: 1 },
  { value: 'Talking / Spoken Word / Poem style', weight: 1 },
  { value: 'Sleepy', weight: 1 },
  { value: 'Drunk', weight: 1 },
  { value: 'Bob Dylan', weight: 1 },
  { value: 'Morrissey', weight: 1 },
  { value: 'Bluegrass harmonies (Cactus Blossoms)', weight: 1 },
  { value: 'Autotune / Highly Processed', weight: 1 },
  { value: 'Breathy / Sexy', weight: 1 },
  { value: 'Big Build, Quiet to Loud', weight: 1 },
  { value: 'Mumbling', weight: 1 },
  { value: 'Gang vocals singalong', weight: 1 },
  { value: 'Duet', weight: 1 },
  { value: 'Pitch-Shifted', weight: 1 },
  { value: 'Female voice', weight: 1 },
  { value: 'Male voice', weight: 1 },
];

const lyricMetaphor = [
  { value: 'Planetary movement', weight: 1 },
  { value: 'Post-apocalypse', weight: 1 },
  { value: 'Ancient Egypt', weight: 1 },
  { value: 'Ice-age', weight: 1 },
  { value: 'Ghost / Haunting', weight: 1 },
  { value: 'Robots', weight: 1 },
  { value: 'Spies', weight: 1 },
  { value: 'Conspiracies', weight: 1 },
  { value: 'Addiction', weight: 1 },
  { value: 'Ancient civilization', weight: 1 },
  { value: 'The end of the world', weight: 1 },
  { value: 'Revolution', weight: 1 },
  { value: 'Trash Island in the Pacific', weight: 1 },
  { value: 'Flavor Town', weight: 1 },
  { value: 'Obsolete Machines', weight: 1 },
  { value: 'Strange Machines', weight: 1 },
  { value: 'Amputation / Phantom Limb', weight: 1 },
  { value: 'Space travel', weight: 1 },
  { value: 'Evolution', weight: 1 },
  { value: 'Lightspeed', weight: 1 },
  { value: 'Extinct is forever', weight: 1 },
  { value: 'The strength of whisky vs steroids', weight: 1 },
  { value: 'Joining a cult', weight: 1 },
  { value: 'Time Travel', weight: 1 },
  { value: 'The Plot to Sister Act 3', weight: 1 },
  { value: 'Expansion of the universe', weight: 1 },
  { value: 'Escape', weight: 1 },
  { value: 'Death', weight: 1 },
];

const lyricSubject = [
  { value: 'Anxiety over technology', weight: 1 },
  { value: 'The Terminator', weight: 1 },
  { value: 'Politics', weight: 1 },
  { value: 'Childhood', weight: 1 },
  { value: 'Death', weight: 1 },
  { value: 'Chicago', weight: 1 },
  { value: 'Ohio', weight: 1 },
  { value: 'California', weight: 1 },
  { value: 'Killing the bird', weight: 1 },
  { value: 'Public Transportation', weight: 1 },
  { value: 'The near future', weight: 1 },
  { value: 'Earth', weight: 1 },
  { value: 'Apartment', weight: 1 },
  { value: 'College', weight: 1 },
  { value: 'Hospital', weight: 1 },
  { value: 'Rejection', weight: 1 },
  { value: 'Christmas', weight: 1 },
  { value: 'New York', weight: 1 },
  { value: 'Mexico', weight: 1 },
  { value: 'Foreigners', weight: 1 },
  { value: 'Predator', weight: 1 },
  { value: 'Perfection', weight: 1 },
  { value: 'Reality', weight: 1 },
  { value: 'Sleeping behind K-Mart', weight: 1 },
  { value: 'Paying your dues', weight: 1 },
  { value: 'Driving your car into a lake, willingly', weight: 1 },
  { value: 'Zodiac killer', weight: 1 },
  { value: 'Jaws locked around your spine', weight: 1 },
  { value: 'Millennial self-consciousness', weight: 1 },
  { value: 'Letting loose', weight: 1 },
  { value: 'Student loans', weight: 1 },
  { value: 'Half-Asleep Thoughts', weight: 1 },
  { value: 'A beautiful scene in nature', weight: 1 },
  { value: 'Family', weight: 1 },
  { value: 'Chess', weight: 1 },
  { value: 'Cold, hardened, steel', weight: 1 },
  { value: 'Eagles', weight: 1 },
  { value: 'Beginnings', weight: 1 },
  { value: 'Pokemon', weight: 1 },
  { value: 'Seinfeld', weight: 1 },
  { value: 'Tetris stacking', weight: 1 },
  { value: 'Wedding / Marriage', weight: 1 },
  { value: 'A nice dinner', weight: 1 },
  { value: 'Fist fight', weight: 1 },
  { value: 'Foot race', weight: 1 },
  { value: 'Napkin origami', weight: 1 },
  { value: 'Wood is technology', weight: 1 },
  { value: 'Hulk Hogan', weight: 1 },
  { value: 'Diaper horse', weight: 1 },
  { value: 'Beer olympics', weight: 1 },
  { value: 'Leather clad vehicles', weight: 1 },
  { value: 'Extremely low jump', weight: 1 },
  { value: 'Mario', weight: 1 },
  { value: 'You decide now, every minute', weight: 1 },
  { value: 'Landing an airplane at the beach', weight: 1 },
  { value: 'Adopting one\'s virginity', weight: 1 },
  { value: 'Skydiving in Equador', weight: 1 },
  { value: 'Riding a bicycle through the fountain of life', weight: 1 },
  { value: 'Knowing too much about someone', weight: 1 },
  { value: 'Looking like Bruce Willis', weight: 1 },
  { value: 'Yeti', weight: 1 },
  { value: 'Tofu Thai Food', weight: 1 },
  { value: 'Dinosaurs', weight: 1 },
  { value: 'You are the party now', weight: 1 },
  { value: 'I\'m you, from the future!', weight: 1 },
  { value: 'Road trip', weight: 1 },
  { value: 'Skid row', weight: 1 },
  { value: 'Solitude', weight: 1 },
  { value: 'Driving through the dust storm', weight: 1 },
  { value: 'Drunk', weight: 1 },
  { value: 'Coming of age', weight: 1 },
  { value: 'Nightmare fuel', weight: 1 },
  { value: 'Police searching your fannypack for contraband, but your genitals are in it', weight: 1 },
];

const melody = [
  { value: 'Acoustic Guitar', weight: 1 },
  { value: 'Electric Guitar', weight: 1 },
  { value: 'Banjo', weight: 1 },
  { value: 'Ukulele', weight: 1 },
  { value: 'Hog-Fiddle', weight: 1 },
  { value: 'Melodica', weight: 1 },
  { value: 'Rhodes', weight: 1 },
  { value: 'Harmonium', weight: 1 },
  { value: 'Bass Guitar', weight: 1 },
  { value: 'Keyboard / Synth', weight: 1 },
  { value: 'Vocal Harmonies', weight: 1 },
  { value: 'Slide Electric Guitar', weight: 1 },
  { value: 'Slide Acoustic Guitar', weight: 1 },
  { value: 'DIY Cello', weight: 1 },
  { value: 'Vocoder Vocals', weight: 1 },
  { value: 'Autotuned Noise / Sample', weight: 1 },
];

const rhythm = [
  { value: 'Rock', weight: 1 },
  { value: 'Swing', weight: 1 },
  { value: 'Surf', weight: 1 },
  { value: 'Reggae', weight: 1 },
  { value: 'Latin', weight: 1 },
  { value: 'Calypso', weight: 1 },
  { value: 'Hip-Hop', weight: 1 },
  { value: 'Funk', weight: 1 },
  { value: 'Dance', weight: 1 },
  { value: 'Pop', weight: 1 },
  { value: 'Punk', weight: 1 },
  { value: 'Metal', weight: 1 },
  { value: 'Blues', weight: 1 },
  { value: 'Shuffle', weight: 1 },
  { value: 'Jazz', weight: 1 },
];

const scale = [
  { value: 'Major', weight: 1 },
  { value: 'Minor', weight: 1 },
];

const strictness = [
  { value: '1-Not Strict', weight: 1 },
  { value: '2-Partially Strict', weight: 1 },
  { value: '3-Very Strict', weight: 1 },
  { value: '4-Totally Strict', weight: 1 },
];

const structure = [
  { value: 'A', weight: 4 },
  { value: 'B', weight: 4 },
  { value: 'C', weight: 2 },
  { value: 'D', weight: 1 },
];

const structureParts = [
  { value: 1, weight: 2 },
  { value: 2, weight: 8 },
  { value: 3, weight: 8 },
  { value: 4, weight: 14 },
  { value: 5, weight: 18 },
  { value: 6, weight: 17 },
  { value: 7, weight: 7 },
  { value: 8, weight: 1 },
  { value: 9, weight: 1 },
];

const texture = [
  { value: 'Electric Guitar', weight: 1 },
  { value: 'Keyboard / Synth', weight: 1 },
  { value: 'Vocal Harmonies', weight: 1 },
  { value: 'Noise Samples', weight: 1 },
  { value: 'Harmonium', weight: 1 },
  { value: 'Slide Guitar', weight: 1 },
  { value: 'Kitchen Sounds', weight: 1 },
  { value: 'DIY Cello', weight: 1 },
  { value: 'Radio', weight: 1 },
  { value: 'Rhodes Loops', weight: 1 },
];

const time = [
  { value: '4/4', weight: 9 },
  { value: '3/4', weight: 5 },
  { value: '6/8', weight: 7 },
  { value: '2/4', weight: 1 },
  { value: '5/4', weight: 2 },
  { value: '7/4', weight: 1 },
  { value: '7/8', weight: 1 },
  { value: '9/8', weight: 1 },
  { value: '11/8', weight: 1 },
  { value: '12/8', weight: 1 },
];

const wildcard = [
  { value: 'Transpose up 1 step @ Part C', weight: 1 },
  { value: 'Minus 1 Beat/Measure @ Part B', weight: 1 },
  { value: 'Emphasize Triplets in each Section', weight: 1 },
  { value: 'Switch Instrument Roles @ Part B', weight: 1 },
  { value: 'Song Must be under 90 seconds', weight: 1 },
  { value: 'Melody Instrument Does Solo', weight: 1 },
  { value: 'Create New Section for Outro', weight: 1 },
  { value: 'Random Key Change in Part C', weight: 1 },
  { value: 'Part C is Pure Noise', weight: 1 },
  { value: 'Sixteenth note emphasis', weight: 1 },
  { value: 'Highly Syncopated Rhythm', weight: 1 },
  { value: 'Resolve to Inverse Maj/Minor', weight: 1 },
  { value: 'One part of song is spoken', weight: 1 },
];

export default {
  bpm,
  harmony,
  key,
  lyricDelivery,
  lyricMetaphor,
  lyricSubject,
  melody,
  rhythm,
  scale,
  strictness,
  structure,
  structureParts,
  texture,
  time,
  wildcard,
};
